### ISSUE TITLE
Tuple "internal" ambiguity error?

### ISSUE THREAD

**Issue by rchen20** [LLNL/camp#108]
Hey @trws, I'm getting this `internal` namespace ambiguity error when building RAJA+Camp with other libraries. It appears that the compiler cannot distinguish between `std::internal`, `mfem::internal`, and the general Camp `internal` (which was left out of the `camp` namespace). Should we just put this into `camp::internal`, or was there a reason you left it out? 

```
/usr/WS1/chen59/allterry/LDRD_Research_Code/TPL_buildOptTOSS3/RAJA/installRAJA/include/camp/tuple.hpp: In function 'std::ostream& operator<<(std::ostream&, const camp::tuple<Args ...>&)':
/usr/WS1/chen59/allterry/LDRD_Research_Code/TPL_buildOptTOSS3/RAJA/installRAJA/include/camp/tuple.hpp:476:3: error: reference to 'internal' is ambiguous
   internal::print_tuple(os, tup, camp::make_idx_seq_t<sizeof...(Args)>{});
   ^~~~~~~~

/usr/tce/packages/gcc/gcc-8.1.0/include/c++/8.1.0/bits/ios_base.h:993:3: note: candidates are: 'std::ios_base& std::internal(std::ios_base&)'
   internal(ios_base& __base)
   ^~~~~~~~

/usr/WS1/chen59/allterry/LDRD_Research_Code/TPL_Submodules/mfem_trt/general/hash.hpp:235:11: note:                 'namespace mfem::internal { }'
 namespace internal
           ^~~~~~~~

/usr/WS1/chen59/allterry/LDRD_Research_Code/TPL_buildOptTOSS3/RAJA/installRAJA/include/camp/tuple.hpp:462:11: note:                 'namespace internal { }'
 namespace internal
           ^~~~~~~~
```

**Comment by trws** [comment]
That should both be in the camp namespace and referenced as `::camp::internal::print_tuple...`

**Comment by rchen20** [comment]
Ah ok, I'll create a PR for this when I have a moment. Thanks!

**Comment by rchen20** [comment]
> That should both be in the camp namespace and referenced as `::camp::internal::print_tuple...`

https://github.com/LLNL/camp/pull/109 This should fix it.
