### ISSUE TITLE
Intel compiler error: cannot overload functions distinguished by return type alone

### ISSUE THREAD

**Issue by gunney1** [LLNL/camp#126]
Build error with intel compilers for recent versions of camp.
To reproduce on rzgenie:
1. module load intel/19.1.2
2. cmake /path/to/camp -DCMAKE_CXX_COMPILER=icpc -DCMAKE_C_COMPILER=icc
3. make
```
Full error dump:
[  6%] Building CXX object blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /g/g10/gunney1/camp-dev/cln/camp/include/camp/camp.hpp(24),
                 from /g/g10/gunney1/camp-dev/cln/camp/src/errors.cpp(11):
/g/g10/gunney1/camp-dev/cln/camp/include/camp/tuple.hpp(114): error: cannot overload functions distinguished by return type alone
      CAMP_HOST_DEVICE constexpr Type& get_inner() noexcept { return val; }
                                       ^

In file included from /g/g10/gunney1/camp-dev/cln/camp/include/camp/camp.hpp(24),
                 from /g/g10/gunney1/camp-dev/cln/camp/src/errors.cpp(11):
/g/g10/gunney1/camp-dev/cln/camp/include/camp/tuple.hpp(138): error: cannot overload functions distinguished by return type alone
      CAMP_HOST_DEVICE constexpr Type& get_inner() noexcept
                                       ^

compilation aborted for /g/g10/gunney1/camp-dev/cln/camp/src/errors.cpp (code 2)
make[2]: *** [CMakeFiles/camp.dir/src/errors.cpp.o] Error 2
make[1]: *** [CMakeFiles/camp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
remark #11074: Inlining inhibited by limit max-size
remark #11074: Inlining inhibited by limit max-total-size
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
```

**Comment by gunney1** [comment]
@rhornung67 I saw it on version 2022.03.2, 2022.10.? and on the develop branch.
I'll try the CXX flags.

**Comment by gunney1** [comment]
The CXX flag fixes this issue.  Note that the spack recipe for camp doesn't have the flag though, so that still fails.

**Comment by rhornung67** [comment]
The issue is that RAJA, camp, etc. require C++14 and the Intel compiler uses the header files from the system default GNU compiler unless you specify otherwise.

Which spack recipe? In Ares?

**Comment by gunney1** [comment]
recipe in spack's builtin repo.

**Comment by rhornung67** [comment]
That shouldn't contain system or compiler version specific flags like that. Mike C. probably sets them in his CMake recipes.

**Comment by gunney1** [comment]
It's set in Ares's compilers.yaml.  So this is an intel issue, not a camp issue, right?

**Comment by rhornung67** [comment]
That's the correct place for the flag.

It's not a camp issue. It's not an Intel issue either. It's due to the fact that the default gcc on TOSS3 machines in LC is 4.9.3 which is very old.

**Comment by gunney1** [comment]
Closing.  This is not a camp issue.  Thanks @rhornung67
