### ISSUE TITLE
camp-v2024.02.1.tar.gz tarball for 2024.02.1 release

### ISSUE THREAD

**Issue by cyrush** [LLNL/camp#149]
Hi All,
For the latest release, can we have a source tarball similar to previous releases?

Thanks!
-Cyrus

**Comment by cyrush** [comment]
If you are curious - one of the differences is:
In side the github created tarball the folder name is:
```
camp-2024.02.1
```

And prev source provided tarball the folder name inside is:

```
camp-v2024.02.1
```

**Comment by rhornung67** [comment]
@cyrush sorry about that -- my bad. The tarball is available in the release now.

**Comment by cyrush** [comment]
@rhornung67 awesome, thanks for quick add!
