### ISSUE TITLE
External CUDA streams

### ISSUE THREAD

**Issue by artv3** [LLNL/camp#44]
Hi Folks, 

We are having trouble keeping track of streams in RAJA. To enable interplay of external software that will also be using CUDA, could there be an option for users to provide an external stream? 

Thanks,
Arturo

**Comment by artv3** [comment]
The use case comes from MFEM, see PR https://github.com/mfem/mfem/pull/1852

**Comment by trws** [comment]
Sure, I think we intended for that to be an option from the start, is the extra constructor for the Cuda resource not an option?

https://github.com/LLNL/camp/blob/master/include/camp/resource/cuda.hpp#L89

It occurs to me looking at it that the device number defaulting to 0 might be inappropriate there, but it should work to let you construct a resource from an arbitrary external stream.

**Comment by davidbeckingsale** [comment]
That constructor is private...

**Comment by trws** [comment]
Yup...  Clearly not firing on all cylinders today. 🤦 

Would making that public solve the issue for you @artv3? I see no reason we couldn't offer that kind of setup, or possibly a maker function if we privatized it to disambiguate between that and the integral version (streams just being ints on the inside).

**Comment by trws** [comment]
Oh, and I think it is used in one spot, the `get_default` method constructs the resource it returns from a stream.

**Comment by artv3** [comment]
Yes that should fix the problem @trws , thanks!
