### ISSUE TITLE
EventProxy does not support getting non-erased event

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/camp#51]
It would be convenient to be able to get a non-erased event type from EventProxy. It seems wasteful to create an erased event when type information is available.

**Comment by trws** [comment]
I agree, we actually seem to have an interface problem I hadn't considered before as well.  The `wait_for` method always takes not only a pointer to an event, but a pointer to a *type-erased* event.  I can add support for this easily, and will shortly, but using strongly typed events is not terribly convenient right now, and I think that's going to need some thought.
