### ISSUE TITLE
Add a strongly typed version of get_event

### ISSUE THREAD

**Issue by artv3** [LLNL/camp#69]
get_event on the erased resource has to return an erased resource unless we give it a template argument and do some other work, it would nice to add a strongly type version of this. 

Possibly have it return an EventProxy or some other mechanism to let people get the strong event out 
    Something like cudaevent* e = e.get_event<cudaevent>()?

**Comment by trws** [comment]
This should now be fixed by #54, closing on that basis.  If there's something more to do here let me know.
