### ISSUE TITLE
CMake `ENABLE_TARGET_OPENMP` doesn't actually enable OpenMP resources

### ISSUE THREAD

**Issue by abbotts** [LLNL/camp#81]
The CMake `-DENABLE_TARGET_OPENMP` flag doesn't look like it actually has any effect. Although this define has the same name, there isn't actually any CMake machinery to turn the config flag into the CPP define
https://github.com/LLNL/camp/blob/72e3f39f35b8511dd55b910f31f4bd0f45f1cfcb/include/camp/defines.hpp#L109

I think this is the root cause of https://github.com/LLNL/RAJA/issues/1111

Because CAMP's build is so bare-bones I don't see an easy solution that I can just implement quickly, other than backout out #46 (which seems like it would break something else). The proper solution would probably involve #41 and some machinery to add OpenMP flags.

**Comment by abbotts** [comment]
This CPP define is now `CAMP_ENABLE_TARGET_OPENMP`, and is correctly set by the CMake define of the same name, so this issue is fixed.

**Comment by barracuda156** [comment]
@abbotts Apparently not: https://github.com/LLNL/CHAI/issues/231
